version: '3'

services:
  api:
    build: api
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    build: db
    ports:
      - "6379:6379"
    volumes:
      - .data:/data
  client:
    build: client
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - api
      - db